### ISSUE TITLE
Chain commands without logout / relogin?

### ISSUE THREAD

**Issue by ingageco** [xwp/vassh#14]
Is there a way to chain the wp commands without the connection being closed and reopened?

Currently I use "vassh wp db reset && vassh wp db import", but the connection is closed in-between commands. Is there a viable alternative that chains them within vassh?

**Comment by westonruter** [comment]
Sure thing. You can just do:

```bash
vassh 'wp db reset && wp db import'
```

**Comment by ingageco** [comment]
Thanks!
