### ISSUE TITLE
Convert into a Vagrant plugin

### ISSUE THREAD

**Issue by westonruter** [xwp/vassh#3]
The functionality provided by vassh is so integral into my workflow now with Vagrant, I think it should somehow be rolled into Vagrant more closely. The best way to do this is via a Vagrant plugin, which I know nothing about.

See [original comment](https://github.com/x-team/vassh/blob/665b71f8540653579035e007c38da3f86d0c5d24/vassh.sh#L20).

**Comment by leoj3n** [comment]
https://github.com/p0deje/vagrant-exec

**Comment by westonruter** [comment]
Wow. Looks like exactly what I wanted.
